//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTrackingMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateInfo { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
    }
}
